// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using miltecti_api.Data;

#nullable disable

namespace miltecti_api.Migrations
{
    [DbContext(typeof(AnuncioContext))]
    [Migration("20250127000002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("miltecti_api.Entities.AnuncioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeAnuncio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAnuncio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Anuncios");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("miltecti_api.Entities.ProdutoEntity", b =>
                {
                    b.HasBaseType("miltecti_api.Entities.AnuncioEntity");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("miltecti_api.Entities.ServicoEntity", b =>
                {
                    b.HasBaseType("miltecti_api.Entities.AnuncioEntity");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Servicos", (string)null);
                });

            modelBuilder.Entity("miltecti_api.Entities.ProdutoEntity", b =>
                {
                    b.HasOne("miltecti_api.Entities.AnuncioEntity", null)
                        .WithOne()
                        .HasForeignKey("miltecti_api.Entities.ProdutoEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("miltecti_api.Entities.ServicoEntity", b =>
                {
                    b.HasOne("miltecti_api.Entities.AnuncioEntity", null)
                        .WithOne()
                        .HasForeignKey("miltecti_api.Entities.ServicoEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
